### PR TITLE
Check that git, bazaar, and mercurial are installed before running tests that require them

### LINKED ISSUE #184: TestGetSources asks for user input, so it hangs indefinitely
`manager_test.go`'s `TestGetSources` hangs indefinitely for me, saying this:

```
=== RUN   TestGetSources
The authenticity of host 'bitbucket.org (104.192.143.2)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)?
no
no pls
pls exit :(
```

The last three lines are mine :)

### PR DESCRIPTION
**Pull request by spenczar**
This is just a quality-of-life thing as a contributor.

Fixes #184.

### CODE REVIEW

**Comment by sdboyer** [comment]
Perfect :)

**Comment by sdboyer** [comment]
I'm kinda surprised and concerned that this would've resulted in a coverage decrease - that would seem to suggest more effects than this should really have. And this is based on the merge result of #185, which is more reasonable to have had those effects...hmm.

Well, not the end of the world.

One nit, though, before I merge - please limit the first line of git commit messages to 50 chars. I'm not as exacting as Tim Pope about [his rules](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html), but I do prefer following them.

**Comment by spenczar** [comment]
Yeah, the coverage decrease seems pretty weird. I've never used codecov, but I'm trying to figure out where the coverage decrease could have come from.

If you like, I'd be happy to amend the commit message and make a new PR to keep the history clean, I'd prefer to be a good citizen 😄

**Comment by sdboyer** [comment]
I appreciate it 😄  - just amending the commit and force-pushing to this PR would be fine. No need for a new one.

**Comment by spenczar** [comment]
This looks it could be a flaky test failure, maybe?
```--- FAIL: TestSignalHandling (0.01s)
	manager_test.go:809: time to send signal: 13.449µs
	manager_test.go:812: time to return from Release(): 96.1µs
	manager_test.go:815: finished too fast (96.1µs); the necessary network request could not have completed yet
	manager_test.go:850: Expected error on statting what should be an absent lock file```

**Comment by sdboyer** [comment]
It is - it's a really hacky way of trying to approximate whether or not the signal handling is occurring correctly. Fails maybe 1/50 times. (I had to move on to other things, so went with the crappy heuristic)

Kicking it, should work on the next run...

**Comment by sdboyer** [comment]
OK, we're good.

**Pull request merged**
